### ISSUE TITLE
Update existing PRs instead of closing and re-opening

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/roller#12]
When we run the cron job we currently close all existing PRs and open a new one, this means that any work on that old PRs branch gets lost and has to be re-pushed.

A better thing to do would be to update the `DEPS` file in the existing PR instead of deleting it and starting again.

**Comment by erickzhao** [comment]
Should close this as it's already implemented 
https://github.com/electron/roller/pull/15

**Comment by codebytere** [comment]
Done
